Employeemanagement.Endpoint/Models/ErrorViewModel.cs
namespace Employeemanagement.Endpoint.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Employeemanagement.Endpoint/Controllers/EmployesController.cs
using EployeeManagment.ApplicationService.Contract.Dtos.Salary;
using EployeeManagment.ApplicationService.Contract.Dtos.WorkHour;
using EployeeManagment.ApplicationService.Contract.IService;
using Microsoft.AspNetCore.Mvc;

namespace Employeemanagement.Endpoint.Controllers
{
    public class EmployesController : Controller
    {
        private readonly IUserService userService;
        private readonly IWorkHourService workHourService;
        private readonly ISalaryService salaryService;
        public EmployesController(IUserService userService, IWorkHourService workHourService, ISalaryService salaryService)
        {
            this.userService = userService;
            this.workHourService = workHourService;
            this.salaryService = salaryService;
        }

        public IActionResult Index()
        {
            var users = userService.GetAll();
            return View(users);
        }
        [HttpGet]
        public IActionResult SetUserSalary(long userId)
        {
            AddSalaryDto dto = new();
            dto.UserId = userId;
            return View(dto);
        }
        [HttpPost]
        public IActionResult SetUserSalary(AddSalaryDto dto)
        {
            salaryService.AddSalary(dto,dto.UserId);
            return Redirect("/Employes/Index");
        }
    }
}

Employeemanagement.Endpoint/Controllers/HomeController.cs
using Employeemanagement.Endpoint.Models;
using EployeeManagment.ApplicationService.Contract.Dtos.User;
using EployeeManagment.ApplicationService.Contract.IService;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Employeemanagement.Endpoint.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUserService userService;

        public HomeController(IUserService userService)
        {
            this.userService = userService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(AddUserDto dto)
        {
            if(userService.AddUser(dto) is true)
            {
                TempData["Success"] = "ثبت کاربر جدید با موفقیت انجام شد";
            }
            else
            {
                TempData["Success"] = "ثبت کاربر جدید با شکست مواجه شد";
            }
            return View(dto);
        }
    }
}

Employeemanagement.Endpoint/Controllers/SalaryController.cs
using EmpeloyeeManagment.ApplicationnService.Services;
using EmployeeManagment.Domain.Models;
using EployeeManagment.ApplicationService.Contract.Dtos.Salary;
using EployeeManagment.ApplicationService.Contract.IService;
using Humanizer;
using Microsoft.AspNetCore.Mvc;

namespace Employeemanagement.Endpoint.Controllers
{
    public class SalaryController : Controller
    {
        private readonly ISalaryService salaryService;

        public SalaryController(ISalaryService salaryService)
        {
            this.salaryService = salaryService;
        }

        [HttpGet]
        public IActionResult Add(long userId)
        {
            AddSalaryDto dto = new();
            dto.UserId = userId;
            return View(dto);
        }
        [HttpPost]
        public IActionResult Add(AddSalaryDto dto)
        {
            salaryService.AddSalary(dto, dto.UserId);
            return Redirect("/Employes/Index");
        }
    }
}

Employeemanagement.Endpoint/Controllers/WorkHourController.cs
using EmpeloyeeManagment.ApplicationnService.Services;
using EmployeeManagment.Domain.Models;
using EployeeManagment.ApplicationService.Contract.Dtos.WorkHour;
using EployeeManagment.ApplicationService.Contract.IService;
using Humanizer;
using Microsoft.AspNetCore.Mvc;

namespace Employeemanagement.Endpoint.Controllers
{
    public class WorkHourController : Controller
    {
        private readonly IWorkHourService workHourService;

        public WorkHourController(IWorkHourService workHourService)
        {
            this.workHourService = workHourService;
        }
        [HttpGet]
        public IActionResult Add(long userId)
        {
            AddWorkHourDto dto = new();
            dto.UserId = userId;
            return View(dto);
        }
        [HttpPost]
        public IActionResult Add(AddWorkHourDto dto)
        {
            workHourService.Add(dto, dto.UserId);
            return Redirect("/Employes/Index");
        }
    }
}

Employeemanagement.Endpoint/Views/Employes/Index.cshtml
@using EployeeManagment.ApplicationService.Contract.Dtos.User;
@model IList<UserDto>
<table class="table">
    <thead>
        <tr>
            <th scope="col">نام</th>
            <th scope="col">نام خانوادگی</th>
            <th scope="col">مجموع ساعت کاری  </th>
            <th scope="col">میزان حقوق به ازای هر ساعت </th>
            <th scope="col">میزان حقوق به ازای هر هفته </th>
            <th scope="col">میزان حقوق به ازای هر ماه </th>
            <th scope="col">افزودن ساعت کاری </th>
            <th scope="col">افزودن حقوق </th>
        </tr>
    </thead>
    @foreach (var user in Model)
    {
        <tbody>

            <tr>
                <th>@user.Name</th>
                <td>@user.Family</td>
                <td>@user.TotalWorkingHours</td>
                <td>@string.Format($"{user.Salary} تومان")</td>
                <td>@string.Format($"{user.SalaryPerWeek} تومان")</td>
                <td>@string.Format($"{user.SalaryPerMonth} تومان")</td>
                <td><a class="btn btn-success" asp-controller="WorkHour" asp-action="Add" asp-route-userId="@user.UserId">افزودن ساعت کاری جدید</a></td>
                <td><a class="btn btn-warning" asp-controller="Salary" asp-action="Add" asp-route-userId="@user.UserId">افزودن حقوق </a></td>
            </tr>
        </tbody>
    }

</table>

Employeemanagement.Endpoint/Views/Home/Index.cshtml
@using EployeeManagment.ApplicationService.Contract.Dtos.User;
@model AddUserDto
@{
    ViewData["Title"] = "Home Page";
}
<h1>ثبت کاربر جدید</h1>
<form asp-controller="Home" asp-action="Index" >

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">نام </label>
        <input type="text" class="form-control" id="exampleFormControlInput1" asp-for="Name">
    </div>

    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">نام خانوادگی  </label>
        <input type="text" class="form-control" id="exampleFormControlInput1" asp-for="Family">
    </div>
    <input type="submit" value="ثبت کاربر جدید" class="btn btn-outline-success" />
</form>

Employeemanagement.Endpoint/Views/Salary/Add.cshtml
@using EployeeManagment.ApplicationService.Contract.Dtos.Salary;
@model AddSalaryDto
<form asp-controller="Employes" asp-action="SetUserSalary">
    <div class="mb-3">
        <input type="hidden" asp-for="UserId" />
        <label class="form-label">دستمزد</label>
        <input type="text" class="form-control" id="exampleInputPassword1" asp-for="Amount">
    </div>
    <button type="submit" class="btn btn-primary">افزودن دستمزد </button>
</form>

Employeemanagement.Endpoint/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employeemanagement.Endpoint</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Employeemanagement.Endpoint.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employeemanagement.Endpoint</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employes" asp-action="Index">لیست کارمندان</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Employeemanagement.Endpoint - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Employeemanagement.Endpoint/Views/WorkHour/Add.cshtml
@using EployeeManagment.ApplicationService.Contract.Dtos.WorkHour;
@model AddWorkHourDto
<form asp-controller="Employes" asp-action="AddHourToUser">
    <input type="hidden" asp-for="UserId" />
    <div class="mb-3">
        <label class="form-label">روز هفته</label>
        <input type="text" class="form-control" aria-describedby="emailHelp" asp-for="DayOfWeek">
    </div>
    <div class="mb-3">
        <label class="form-label">زمان شروع کار </label>
        <input type="time" class="form-control" id="exampleInputPassword1" asp-for="Startworkhour">
    </div>
    <div class="mb-3">
        <label class="form-label">زمان پایان کار </label>
        <input type="time" class="form-control" id="exampleInputPassword1" asp-for="Endtworkhour">
    </div>
    <button type="submit" class="btn btn-primary">افزودن ساعت کاری</button>
</form>